CREATE DATABASE VENDAS;

USE VENDAS;

CREATE TABLE PRODUTOS(
    ID_PRODUTO INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    DESCRICAO VARCHAR(30),
    ESTOQUE_PRODUTO INT NOT NULL,
    PRECO_PRODUTO DOUBLE
    );
   
 CREATE TABLE VENDA(
 
    ID_VENDA INT NOT  NULL PRIMARY KEY AUTO_INCREMENT,
    NUMERO_VENDA INT NOT NULL,
    ID_PRODUTO INT,
    QUANTIDADE INT
   
 );
 
 INSERT INTO PRODUTOS (DESCRICAO, ESTOQUE_PRODUTO, PRECO_PRODUTO) VALUE ("FRANGO", 30, 8);
 
 SELECT * FROM PRODUTOS;
 
 insert into VENDA( NUMERO_VENDA, ID_PRODUTO, QUANTIDADE) VALUES(2, 4, 6);
 
 DELIMITER $$
 
 CREATE TRIGGER ATUALIZAR_ESTOQUE AFTER INSERT
 ON VENDA
 FOR EACH ROW
 
 BEGIN
 
  UPDATE PRODUTOS SET ESTOQUE_PRODUTO = ESTOQUE_PRODUTO - NEW.QUANTIDADE WHERE ID_PRODUTO = NEW.ID_PRODUTO;
  
END $$

DELIMITER ;
